# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "kustomize-${version}";
  version = "v2.0.3";
  rev = "a6f65144121d1955266b0cd836ce954c04122dc8";

  goPackagePath = "sigs.k8s.io/kustomize";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/kubernetes-sigs/kustomize.git";
    sha256 = "1dfkpx9rllj1bzm5f52bx404kdds3zx1h38yqri9ha3p3pcb1bbb";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
